version: "3.8" 

services: 

  postgres: 
    image: postgres
    container_name: ${CONTAINER_NAME}
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data: