version: "3.8"

services:
  postgres:
    image: postgres
    container_name: SEDECODE
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: "123456"  # Sin espacio entre "POSTGRES_PASSWORD" y el valor
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "sedecode"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: